export default {
  container: {
    zIndex: 1006,
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    height: '100vh',
    width: '100vw',
  },
  overlay: {
    zIndex: 1005,
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    // backgroundAttchment: 'fixed',
    backgroundColor: 'rgba(0, 0, 0, .75)',
    // backgroundImage: `url(${Score})`,
    // backgroundSize: 'cover',
    // backgroundPositionX: 'center',
    // backgroundPositionY: 'center',
    // backgroundRepeat: 'no-repeat',
  },
  box: { backgroundColor: 'black', minHeight: '75vh', minWidth: '75vw' },
};
